const ROOT = 'ROOT';
const HOME = 'HOME';
const CATEGORY = 'CATEGORY';
const CONTACT = 'CONTACT';
const ADD_CONTACT = 'ADD_CONTACT';
const EDIT_CONTACT = 'EDIT_CONTACT';
const ACCOUNT = 'ACCOUNT';
const SEARCH = 'SEARCH';

export default {
  ROOT,
  HOME,
  CATEGORY,
  CONTACT,
  ADD_CONTACT,
  EDIT_CONTACT,
  ACCOUNT,
  SEARCH,
};
